Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -34,11 +34,10 @@ jobs:
         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
-        if: ${{ failure() }}
-        {
-          echo "There are errors in your code. Kindly correct them before build"
-          exit 1
-        }
+        if: ${{ failure() }}         
+        echo "There are errors in your code. Kindly correct them before build"
+        exit 1
+      
         
     - name: Test with pytest
       run: |
